repos:
-   repo: https://github.com/tekwizely/pre-commit-golang
    rev: v0.8.2
    hooks:
    -   id: go-build-repo-mod
    -   id: go-test-repo-mod
    -   id: go-imports
    -   id: golangci-lint-repo-mod
