name: Release stable

env:
  REPO_OWNER: ${{ vars.REPO_OWNER }}
  REPO_WEBSITE: ${{ vars.REPO_WEBSITE }}
  REPO_DESCRIPTION: ${{ vars.REPO_DESCRIPTION }}
  REPO_MAINTAINER: ${{ vars.REPO_MAINTAINER }}
  REPO_AUTHOR_NAME: ${{ vars.REPO_AUTHOR_NAME }}
  REPO_AUTHOR_EMAIL: ${{ vars.REPO_AUTHOR_EMAIL }}
  REPO_BINARY_NAME: ${{ vars.REPO_BINARY_NAME }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GORELEASER_GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  FURY_PUSH_TOKEN: ${{ secrets.FURY_PUSH_TOKEN }}
  FURY_USERNAME: ${{ secrets.FURY_USERNAME }}
  GORELEASER_CURRENT_TAG: ${{ github.event.client_payload.tag_name }}

on:
  repository_dispatch:
    types: [release_stable]

jobs:
  release_stable:
    name: Release stable version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go ${{ vars.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ vars.GO_VERSION }}

      - name: Create stable release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.client_payload.tag_name }}
          name: ${{ github.event.client_payload.tag_name }}
          body: ${{ env.CHANGELOG }}
          draft: false
          prerelease: false

      - name: View environmental variables
        run: env

      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: ~> v2
          args: release --clean
